const initialDetails = [
    {
        id: 1,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        maquina: "Lorem ipsu",
        pais: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 2,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        maquina: "Lorem ipsu",
        pais: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 3,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        pais: "Lorem ipsu",
        maquina: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 4,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        pais: "Lorem ipsu",
        maquina: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 5,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        pais: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        maquina: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 6,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        pais: "Lorem ipsu",
        maquina: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 7,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        pais: "Lorem ipsu",
        maquina: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    },
    {
        id: 8,
        name: "Lorem ipsu",
        motivo: "Lorem ipsu",
        eficacia: "Lorem ipsu",
        pais: "Lorem ipsu",
        maquina: "Lorem ipsu",
        description: "Lorem ipsu",
        place: "Lorem ipsu",
        area: "Lorem ipsu",
        fecha: "Lorem ipsu",
        status: "Lorem ipsu",
        asign: "Lorem ipsu"
    }
];

export default initialDetails;